/* ============================================================
 * 释义多语言表：学习语言单词的释义跟随界面语言显示
 * 查找顺序：界面语言 → 英语注释 → 词库原释义(中文)
 * ============================================================ */
window.WORD_MEANINGS = {
    'en': {
        me: 'I; the person speaking', you: 'the person spoken to', he: 'that man or boy',
        she: 'that woman or girl', it: 'that thing', we: 'you and I',
        they: 'those people', us: 'you and I (object)', them: 'those people (object)',
        my: 'belonging to me', your: 'belonging to you', his: 'belonging to him',
        her: 'belonging to her', its: 'belonging to it', our: 'belonging to us',
        need: 'to require; must have', want: 'to wish for', have: 'to own; to hold',
        use: 'to put into action', get: 'to obtain; to receive', eat: 'to put food in your mouth',
        food: 'things people eat', drink: 'to swallow liquid', water: 'the drink of life',
        hungry: 'wanting food', rice: 'white grain food', bread: 'baked food from flour',
        egg: 'a round food from birds', noodle: 'long strips of food', meat: 'animal flesh as food',
        sleep: 'to rest with eyes closed', bed: 'furniture for sleeping', dream: 'pictures in the mind during sleep',
        tired: 'needing rest', night: 'the dark time of the day', what: 'asking for information',
        who: 'asking which person', where: 'asking in which place', when: 'asking at what time',
        why: 'asking for what reason', how: 'asking in what way', because: 'for the reason that',
        if: 'on the condition that', and: 'also; together with', but: 'however',
        teach: 'to help someone learn', learn: 'to get knowledge', help: 'to make things easier for someone',
        please: 'a polite word when asking', give: 'to hand over to someone', eye: 'you see with it',
        ear: 'you hear with it', mouth: 'you eat and speak with it', nose: 'you smell with it',
        face: 'the front of the head', hand: 'the body part with fingers', foot: 'the body part you stand on',
        leg: 'connects foot to body', arm: 'connects hand to body', head: 'the top part of the body with the face',
        see: 'to notice with the eyes', look: 'to turn the eyes toward', hear: 'to notice with the ears',
        listen: 'to pay attention to sound', speak: 'to say words', think: 'to use the mind',
        know: 'to have in the mind as fact', feel: 'to sense; to have emotions', mind: 'the part that thinks',
        idea: 'a thought; a plan in the mind', house: 'a building where people live', home: 'the place where you live',
        room: 'a part of a house', door: 'you open it to enter', window: 'glass opening in a wall',
        open: 'not closed', close: 'to shut', light: 'brightness; a lamp',
        key: 'small metal tool for locks', lock: 'a device that keeps doors shut', table: 'furniture with a flat top',
        chair: 'furniture for sitting', desk: 'a table for work or study', sofa: 'a long soft seat',
        shelf: 'a flat board for things', bowl: 'a round deep dish', plate: 'a flat dish',
        cup: 'a small drinking vessel', spoon: 'a tool for eating soup', chopsticks: 'two sticks for eating',
        fork: 'a tool with points for eating', knife: 'a tool for cutting', cook: 'to prepare food with heat',
        kitchen: 'the room for cooking', bottle: 'a container for liquids', box: 'a container with corners',
        bag: 'a soft container you carry', clothes: 'things you wear', shirt: 'clothing for the upper body',
        shoe: 'clothing for the feet', 你: 'you', 我: 'I; me',
        他: 'he; him', 她: 'she; her', 们: 'plural marker (they, we)',
        好: 'good; well', 是: 'to be; yes', 在: 'at; to exist',
        不: 'no; not', 有: 'to have; there is', 吃: 'to eat',
        喝: 'to drink', 食: 'food', 物: 'thing; object',
        水: 'water', 谢: 'to thank', 再: 'again',
        见: 'to see; to meet', 晚: 'night; late', 安: 'peace; safe',
        什: 'what (什么)', 这: 'this', 那: 'that',
        哪: 'where; which', 吗: 'question particle', 大: 'big',
        小: 'small', 多: 'many; much', 少: 'few; little',
        上: 'up; on; above', 下: 'down; below', 中: 'middle; in',
        天: 'day; sky', 月: 'moon; month', 日: 'sun; day',
        人: 'person; people', 口: 'mouth; opening', 手: 'hand',
        目: 'eye', 耳: 'ear', 一: 'one',
        二: 'two', 三: 'three', 四: 'four',
        五: 'five', 山: 'mountain', 火: 'fire',
        石: 'stone', 田: 'field', 土: 'soil; earth',
        я: 'I', а: 'and; but', да: 'yes',
        нет: 'no', он: 'he', мы: 'we',
        кот: 'cat (male)', дом: 'house; home', сыр: 'cheese',
        чай: 'tea', мяч: 'ball', мама: 'mom',
        папа: 'dad', вода: 'water', окно: 'window',
        небо: 'sky', рыба: 'fish', рука: 'hand; arm',
        красный: 'red', синий: 'blue', зелёный: 'green',
        собака: 'dog', погода: 'weather', молоко: 'milk',
        спасибо: 'thank you', a: 'one; any', i: 'the person speaking',
        do: 'to perform an action', go: 'to move; to travel', up: 'toward a higher place',
        no: 'not at all; used to refuse', is: 'be (3rd person)', in: 'inside',
        on: 'on top of', to: 'toward; used before a verb', red: 'the colour of blood',
        blue: 'the colour of the sky', green: 'the colour of grass', yellow: 'the colour of the sun',
        cat: 'a small pet animal', dog: 'a pet animal that barks', sun: 'the star that gives us light',
        run: 'to move fast on foot', love: 'to like someone very much', time: 'hours, minutes; when things happen',
        book: 'pages you read', milk: 'white drink from cows', apple: 'a round fruit',
        music: 'pleasant sounds; songs', fish: 'an animal that swims', bird: 'an animal that flies',
        star: 'a point of light in the night sky', fight: 'to battle; to hit each other', ball: 'a round toy for games',
        tree: 'a tall plant with a trunk', discovery: 'finding something for the first time', thanks: 'words that show you are grateful',
        smile: 'a happy face', hello: 'a greeting', walk: 'to move on foot',
        talk: 'to speak with someone', nǐhǎo: 'hello', wǒmen: 'we; us',
        xièxie: 'thank you', zàijiàn: 'goodbye', wǎnān: 'good night',
        shénme: 'what', zhèlǐ: 'here', nàlǐ: 'there',
        xiànzài: 'now', jīntiān: 'today', míngtiān: 'tomorrow',
        xuésheng: 'student', lǎoshī: 'teacher', péngyou: 'friend',
        shuǐguǒ: 'fruit', chīfàn: 'to eat (a meal)', hēshuǐ: 'to drink water',
        shǒujī: 'mobile phone', diànnǎo: 'computer', dàxiǎo: 'size; big and small',
        ты: 'you', она: 'she', они: 'they',
        вы: 'you (formal/plural)', меня: 'me', тебя: 'you (object)',
        нас: 'us', нужно: 'it is necessary', надо: 'one must',
        хочу: 'I want', можно: 'one may', здесь: 'here',
        еда: 'food', хлеб: 'bread', мясо: 'meat',
        кушать: 'to eat', пить: 'to drink', голодный: 'hungry',
        жажда: 'thirst', вкусно: 'tasty', спать: 'to sleep',
        кровать: 'bed', устал: 'tired', сон: 'sleep; dream',
        ночь: 'night', что: 'what', кто: 'who',
        где: 'where', когда: 'when', почему: 'why',
        как: 'how', потому: 'because', если: 'if',
        сколько: 'how many', куда: 'where to', учить: 'to teach; to learn',
        научите: 'please teach me', помогите: 'please help', дайте: 'please give',
        пожалуйста: 'please; you are welcome', глаз: 'eye', ухо: 'ear',
        рот: 'mouth', нос: 'nose', нога: 'leg; foot',
        голова: 'head', лицо: 'face', палец: 'finger',
        сердце: 'heart', видеть: 'to see', слушать: 'to listen',
        говорить: 'to speak', думать: 'to think', знать: 'to know',
        комната: 'room', дверь: 'door', ключ: 'key',
        открыть: 'to open', закрыть: 'to close', свет: 'light; lamp',
        стол: 'table', стул: 'chair', тарелка: 'plate',
        чашка: 'cup', ложка: 'spoon', вилка: 'fork',
        нож: 'knife', 你好: 'hello', 谢谢: 'thank you',
        再见: 'goodbye', 晚安: 'good night', 你们: 'you (plural)',
        我们: 'we; us', 他们: 'they', 她们: 'they (women)',
        什么: 'what', 不是: 'is not', 吃饭: 'to eat (a meal)',
        喝水: 'to drink water', 食物: 'food', 没有: 'not have; there is not',
        早上: 'morning', 这个: 'this one', 那个: 'that one',
        这里: 'here', 那里: 'there', 大小: 'size; big and small',
        多少: 'how many; how much', 上下: 'up and down; roughly', 十五: 'fifteen',
        五十: 'fifty', 三十: 'thirty', 今天: 'today',
        明天: 'tomorrow', 天上: 'in the sky', 早晚: 'sooner or later; morning and evening',
        日月: 'sun and moon', 人口: 'population', 耳目: 'what one sees and hears',
        手中: 'in hand', 水中: 'in the water', 山口: 'mountain pass',
        山水: 'landscape', 火山: 'volcano', 水土: 'water and soil; climate',
        田里: 'in the field', 山下: 'at the foot of the mountain', 石头: 'stone',
        天下: 'the world; all under heaven', 水里: 'in the water', 手上: 'in the hand',
        土里: 'in the soil', 大人: 'adult', 好人: 'good person',
        明日: 'tomorrow (formal)', 今日: 'today (formal)', 水火: 'water and fire',
    },
    'ja': {
        a: '一つの', i: '私', do: 'する',
        go: '行く', up: '上へ', no: 'いいえ',
        it: 'それ', is: 'です（三人称）', in: 'の中',
        on: 'の上に', to: '〜へ', we: '私たち',
        he: '彼', me: '私', red: '赤',
        blue: '青', green: '緑', yellow: '黄色',
        cat: '猫', dog: '犬', sun: '太陽',
        run: '走る', eat: '食べる', box: '箱',
        love: '愛', time: '時間', book: '本',
        milk: '牛乳', apple: 'りんご', water: '水',
        house: '家', music: '音楽', fish: '魚',
        bird: '鳥', star: '星', egg: '卵',
        fight: '戦う', ball: 'ボール', tree: '木',
        discovery: '発見', you: 'あなた', she: '彼女',
        need: '必要とする', food: '食べ物', drink: '飲む',
        sleep: '眠る', what: '何', teach: '教える',
        learn: '学ぶ', help: '助ける', eye: '目',
        ear: '耳', mouth: '口', nose: '鼻',
        hand: '手', idea: '考え', door: 'ドア',
        bed: 'ベッド', chair: '椅子', table: 'テーブル',
        cup: 'カップ', bowl: '茶碗', open: '開く',
        close: '閉める', light: '光；灯', thanks: 'ありがとう',
        smile: '微笑み', hello: 'こんにちは', walk: '歩く',
        talk: '話す', я: '私', а: 'そして',
        да: 'はい', нет: 'いいえ', он: '彼',
        мы: '私たち', кот: '猫', дом: '家',
        сыр: 'チーズ', чай: 'お茶', мяч: 'ボール',
        мама: 'ママ', папа: 'パパ', вода: '水',
        окно: '窓', небо: '空', рыба: '魚',
        рука: '手・腕', красный: '赤い', синий: '青い',
        зелёный: '緑の', собака: '犬', погода: '天気',
        молоко: '牛乳', спасибо: 'ありがとう', 你: 'あなた',
        我: '私', 他: '彼', 她: '彼女',
        们: '複数（たち）', 好: '良い', 是: 'です',
        在: '〜にいる', 不: 'ない', 有: 'ある・持つ',
        吃: '食べる', 喝: '飲む', 食: '食べ物',
        物: '物', 水: '水', 谢: '感謝する',
        再: 'また', 见: '会う・見る', 晚: '夜・遅い',
        安: '安らか', 什: '何（什么）', 这: 'これ',
        那: 'あれ', 哪: 'どこ', 吗: '疑問の助詞',
        大: '大きい', 小: '小さい', 多: '多い',
        少: '少ない', 上: '上', 下: '下',
        中: '中', 天: '空・日', 月: '月',
        日: '日・太陽', 人: '人', 口: '口',
        手: '手', 目: '目', 耳: '耳',
        一: '一', 二: '二', 三: '三',
        四: '四', 五: '五', 山: '山',
        火: '火', 石: '石', 田: '田んぼ',
        土: '土', they: '彼ら', us: '私を',
        them: '彼らを', my: '私の', your: 'あなたの',
        his: '彼の', her: '彼女の', its: 'それの',
        our: '私たちの', want: '欲しい', have: '持っている',
        use: '使う', get: '得る', hungry: 'お腹が空いた',
        rice: 'ご飯・米', bread: 'パン', noodle: '麺',
        meat: '肉', dream: '夢', tired: '疲れた',
        night: '夜', who: '誰', where: 'どこ',
        when: 'いつ', why: 'なぜ', how: 'どのように',
        because: 'なぜなら', if: 'もし', and: 'そして',
        but: 'しかし', please: 'お願いします', give: 'あげる',
        face: '顔', foot: '足', leg: '脚',
        arm: '腕', head: '頭', see: '見える',
        look: '見る', hear: '聞こえる', listen: '聞く',
        speak: '話す', think: '考える', know: '知っている',
        feel: '感じる', mind: '心・思考', home: '家',
        room: '部屋', window: '窓', key: '鍵',
        lock: '錠前', desk: '机', sofa: 'ソファ',
        shelf: '棚', plate: '皿', spoon: 'スプーン',
        chopsticks: '箸', fork: 'フォーク', knife: 'ナイフ',
        cook: '料理する', kitchen: '台所', bottle: '瓶',
        bag: 'かばん', clothes: '服', shirt: 'シャツ',
        shoe: '靴', nǐhǎo: 'こんにちは', wǒmen: '私たち',
        xièxie: 'ありがとう', zàijiàn: 'さようなら', wǎnān: 'おやすみなさい',
        shénme: '何', zhèlǐ: 'ここ', nàlǐ: 'あそこ',
        xiànzài: '今', jīntiān: '今日', míngtiān: '明日',
        xuésheng: '学生', lǎoshī: '先生', péngyou: '友達',
        shuǐguǒ: '果物', chīfàn: 'ご飯を食べる', hēshuǐ: '水を飲む',
        shǒujī: '携帯電話', diànnǎo: 'パソコン', dàxiǎo: '大きさ',
        你好: 'こんにちは', 谢谢: 'ありがとう', 再见: 'さようなら',
        晚安: 'おやすみなさい', 你们: 'you (plural)', 我们: '私たち',
        他们: 'they', 她们: 'they (women)', 什么: '何',
        不是: 'is not', 吃饭: 'ご飯を食べる', 喝水: '水を飲む',
        食物: 'food', 没有: 'not have; there is not', 早上: 'morning',
        这个: 'this one', 那个: 'that one', 这里: 'ここ',
        那里: 'あそこ', 大小: '大きさ', 多少: 'how many; how much',
        上下: 'up and down; roughly', 十五: 'fifteen', 五十: 'fifty',
        三十: 'thirty', 今天: '今日', 明天: '明日',
        天上: 'in the sky', 早晚: 'sooner or later; morning and evening', 日月: 'sun and moon',
        人口: 'population', 耳目: 'what one sees and hears', 手中: 'in hand',
        水中: 'in the water', 山口: 'mountain pass', 山水: 'landscape',
        火山: 'volcano', 水土: 'water and soil; climate', 田里: 'in the field',
        山下: 'at the foot of the mountain', 石头: 'stone', 天下: 'the world; all under heaven',
        水里: 'in the water', 手上: 'in the hand', 土里: 'in the soil',
        大人: 'adult', 好人: 'good person', 明日: 'tomorrow (formal)',
        今日: 'today (formal)', 水火: 'water and fire',
    },
    'ko': {
        a: '하나의', i: '나', do: '하다',
        go: '가다', up: '위로', no: '아니요',
        it: '그것', is: '이다 (3인칭)', in: '안에',
        on: '위에', to: '~로', we: '우리',
        he: '그', me: '나', red: '빨간색',
        blue: '파란색', green: '초록색', yellow: '노란색',
        cat: '고양이', dog: '개', sun: '태양',
        run: '달리다', eat: '먹다', box: '상자',
        love: '사랑', time: '시간', book: '책',
        milk: '우유', apple: '사과', water: '물',
        house: '집', music: '음악', fish: '물고기',
        bird: '새', star: '별', egg: '계란',
        fight: '싸우다', ball: '공', tree: '나무',
        discovery: '발견', you: '당신', she: '그녀',
        need: '필요하다', food: '음식', drink: '마시다',
        sleep: '자다', what: '무엇', teach: '가르치다',
        learn: '배우다', help: '돕다', eye: '눈',
        ear: '귀', mouth: '입', nose: '코',
        hand: '손', idea: '생각', door: '문',
        bed: '침대', chair: '의자', table: '테이블',
        cup: '컵', bowl: '그릇', open: '열다',
        close: '닫다', light: '빛; 등', thanks: '감사합니다',
        smile: '미소', hello: '안녕하세요', walk: '걷다',
        talk: '말하다', я: '나', а: '그리고',
        да: '네', нет: '아니요', он: '그',
        мы: '우리', кот: '고양이', дом: '집',
        сыр: '치즈', чай: '차', мяч: '공',
        мама: '엄마', папа: '아빠', вода: '물',
        окно: '창문', небо: '하늘', рыба: '물고기',
        рука: '손; 팔', красный: '빨간', синий: '파란',
        зелёный: '초록의', собака: '개', погода: '날씨',
        молоко: '우유', спасибо: '고맙습니다', 你: '당신',
        我: '나', 他: '그', 她: '그녀',
        们: '복수 접미사', 好: '좋다', 是: '이다',
        在: '있다; ~에서', 不: '아니', 有: '있다; 가지다',
        吃: '먹다', 喝: '마시다', 食: '음식',
        物: '물건', 水: '물', 谢: '감사하다',
        再: '다시', 见: '보다; 만나다', 晚: '밤; 늦은',
        安: '평안', 什: '무엇(什么)', 这: '이것',
        那: '저것', 哪: '어디', 吗: '의문 조사',
        大: '크다', 小: '작다', 多: '많다',
        少: '적다', 上: '위', 下: '아래',
        中: '가운데', 天: '하늘; 날', 月: '달; 월',
        日: '해; 날', 人: '사람', 口: '입',
        手: '손', 目: '눈', 耳: '귀',
        一: '일', 二: '이', 三: '삼',
        四: '사', 五: '오', 山: '산',
        火: '불', 石: '돌', 田: '밭',
        土: '흙', they: '그들', us: '우리를',
        them: '그들을', my: '나의', your: '당신의',
        his: '그의', her: '그녀의', its: '그것의',
        our: '우리의', want: '원하다', have: '가지다',
        use: '사용하다', get: '얻다', hungry: '배고픈',
        rice: '쌀; 밥', bread: '빵', noodle: '면',
        meat: '고기', dream: '꿈', tired: '피곤한',
        night: '밤', who: '누구', where: '어디',
        when: '언제', why: '왜', how: '어떻게',
        because: '때문에', if: '만약', and: '그리고',
        but: '그러나', please: '부탁합니다', give: '주다',
        face: '얼굴', foot: '발', leg: '다리',
        arm: '팔', head: '머리', see: '보이다',
        look: '보다', hear: '들리다', listen: '듣다',
        speak: '말하다', think: '생각하다', know: '알다',
        feel: '느끼다', mind: '마음', home: '집',
        room: '방', key: '열쇠', lock: '자물쇠',
        desk: '책상', sofa: '소파', shelf: '선반',
        plate: '접시', spoon: '숟가락', chopsticks: '젓가락',
        fork: '포크', knife: '칼', cook: '요리하다',
        kitchen: '부엌', bottle: '병', bag: '가방',
        clothes: '옷', shirt: '셔츠', shoe: '신발',
        nǐhǎo: '안녕하세요', wǒmen: '우리', xièxie: '감사합니다',
        zàijiàn: '안녕히 가세요', wǎnān: '안녕히 자세요', shénme: '무엇',
        zhèlǐ: '여기', nàlǐ: '저기', xiànzài: '지금',
        jīntiān: '오늘', míngtiān: '내일', xuésheng: '학생',
        lǎoshī: '선생님', péngyou: '친구', shuǐguǒ: '과일',
        chīfàn: '식사하다', hēshuǐ: '물 마시기', shǒujī: '휴대폰',
        diànnǎo: '컴퓨터', dàxiǎo: '크기', 你好: '안녕하세요',
        谢谢: '감사합니다', 再见: '안녕히 가세요', 晚安: '안녕히 자세요',
        你们: 'you (plural)', 我们: '우리', 他们: 'they',
        她们: 'they (women)', 什么: '무엇', 不是: 'is not',
        吃饭: '식사하다', 喝水: '물 마시기', 食物: 'food',
        没有: 'not have; there is not', 早上: 'morning', 这个: 'this one',
        那个: 'that one', 这里: '여기', 那里: '저기',
        大小: '크기', 多少: 'how many; how much', 上下: 'up and down; roughly',
        十五: 'fifteen', 五十: 'fifty', 三十: 'thirty',
        今天: '오늘', 明天: '내일', 天上: 'in the sky',
        早晚: 'sooner or later; morning and evening', 日月: 'sun and moon', 人口: 'population',
        耳目: 'what one sees and hears', 手中: 'in hand', 水中: 'in the water',
        山口: 'mountain pass', 山水: 'landscape', 火山: 'volcano',
        水土: 'water and soil; climate', 田里: 'in the field', 山下: 'at the foot of the mountain',
        石头: 'stone', 天下: 'the world; all under heaven', 水里: 'in the water',
        手上: 'in the hand', 土里: 'in the soil', 大人: 'adult',
        好人: 'good person', 明日: 'tomorrow (formal)', 今日: 'today (formal)',
        水火: 'water and fire',
    },
    'ru': {
        a: 'один; какой-либо', i: 'я', do: 'делать',
        go: 'идти; ехать', up: 'вверх', no: 'нет',
        it: 'оно; это', is: 'есть (3-е лицо)', in: 'в',
        on: 'на', to: 'к; частица глагола', we: 'мы',
        he: 'он', me: 'я; меня', red: 'красный',
        blue: 'синий; голубой', green: 'зелёный', yellow: 'жёлтый',
        cat: 'кот; кошка', dog: 'собака', sun: 'солнце',
        run: 'бежать', eat: 'есть; кушать', box: 'коробка',
        love: 'любить; любовь', time: 'время', book: 'книга',
        milk: 'молоко', apple: 'яблоко', water: 'вода',
        house: 'дом', music: 'музыка', fish: 'рыба',
        bird: 'птица', star: 'звезда', egg: 'яйцо',
        fight: 'драться; сражаться', ball: 'мяч', tree: 'дерево',
        discovery: 'открытие', you: 'ты; вы', she: 'она',
        need: 'нуждаться', food: 'еда', drink: 'пить',
        sleep: 'спать', what: 'что', teach: 'учить; преподавать',
        learn: 'учиться', help: 'помогать', eye: 'глаз',
        ear: 'ухо', mouth: 'рот', nose: 'нос',
        hand: 'рука (кисть)', idea: 'идея; мысль', door: 'дверь',
        bed: 'кровать', chair: 'стул', table: 'стол',
        cup: 'чашка', bowl: 'миска', open: 'открыть',
        close: 'закрыть', light: 'свет; лампа', thanks: 'спасибо',
        smile: 'улыбка; улыбаться', hello: 'привет; здравствуйте', walk: 'гулять; ходить',
        talk: 'говорить', я: 'я', а: 'а; и',
        да: 'да', нет: 'нет', он: 'он',
        мы: 'мы', кот: 'кот', дом: 'дом',
        сыр: 'сыр', чай: 'чай', мяч: 'мяч',
        мама: 'мама', папа: 'папа', вода: 'вода',
        окно: 'окно', небо: 'небо', рыба: 'рыба',
        рука: 'рука', красный: 'красный', синий: 'синий',
        зелёный: 'зелёный', собака: 'собака', погода: 'погода',
        молоко: 'молоко', спасибо: 'спасибо', 你: 'ты',
        我: 'я', 他: 'он', 她: 'она',
        们: 'суффикс множ. числа', 好: 'хороший', 是: 'быть; да',
        在: 'в; находиться', 不: 'не', 有: 'иметь; есть',
        吃: 'есть', 喝: 'пить', 食: 'еда',
        物: 'вещь', 水: 'вода', 谢: 'благодарить',
        再: 'снова', 见: 'видеть', 晚: 'вечер; поздно',
        安: 'спокойный', 什: 'что (什么)', 这: 'это',
        那: 'то', 哪: 'где; который', 吗: 'вопрос. частица',
        大: 'большой', 小: 'маленький', 多: 'много',
        少: 'мало', 上: 'верх; на', 下: 'низ; под',
        中: 'середина', 天: 'небо; день', 月: 'луна; месяц',
        日: 'солнце; день', 人: 'человек', 口: 'рот',
        手: 'рука', 目: 'глаз', 耳: 'ухо',
        一: 'один', 二: 'два', 三: 'три',
        四: 'четыре', 五: 'пять', 山: 'гора',
        火: 'огонь', 石: 'камень', 田: 'поле',
        土: 'земля', they: 'они', us: 'нам; нас',
        them: 'им; их', my: 'мой', your: 'твой; ваш',
        his: 'его', her: 'её', its: 'его (о предмете)',
        our: 'наш', want: 'хотеть', have: 'иметь',
        use: 'использовать', get: 'получать', hungry: 'голодный',
        rice: 'рис', bread: 'хлеб', noodle: 'лапша',
        meat: 'мясо', dream: 'мечта; сон', tired: 'уставший',
        night: 'ночь', who: 'кто', where: 'где',
        when: 'когда', why: 'почему', how: 'как',
        because: 'потому что', if: 'если', and: 'и',
        but: 'но', please: 'пожалуйста', give: 'давать',
        face: 'лицо', foot: 'ступня; нога', leg: 'нога',
        arm: 'рука', head: 'голова', see: 'видеть',
        look: 'смотреть', hear: 'слышать', listen: 'слушать',
        speak: 'говорить', think: 'думать', know: 'знать',
        feel: 'чувствовать', mind: 'разум', home: 'дом; дома',
        room: 'комната', key: 'ключ', lock: 'замок',
        desk: 'парта; письменный стол', sofa: 'диван', shelf: 'полка',
        plate: 'тарелка', spoon: 'ложка', chopsticks: 'палочки для еды',
        fork: 'вилка', knife: 'нож', cook: 'готовить',
        kitchen: 'кухня', bottle: 'бутылка', bag: 'сумка',
        clothes: 'одежда', shirt: 'рубашка', shoe: 'ботинок; туфля',
        nǐhǎo: 'привет', wǒmen: 'мы', xièxie: 'спасибо',
        zàijiàn: 'до свидания', wǎnān: 'доброй ночи', shénme: 'что',
        zhèlǐ: 'здесь', nàlǐ: 'там', xiànzài: 'сейчас',
        jīntiān: 'сегодня', míngtiān: 'завтра', xuésheng: 'студент; ученик',
        lǎoshī: 'учитель', péngyou: 'друг', shuǐguǒ: 'фрукты',
        chīfàn: 'есть (принимать пищу)', hēshuǐ: 'пить воду', shǒujī: 'мобильный телефон',
        diànnǎo: 'компьютер', dàxiǎo: 'размер', 你好: 'привет',
        谢谢: 'спасибо', 再见: 'до свидания', 晚安: 'доброй ночи',
        你们: 'you (plural)', 我们: 'мы', 他们: 'they',
        她们: 'they (women)', 什么: 'что', 不是: 'is not',
        吃饭: 'есть (принимать пищу)', 喝水: 'пить воду', 食物: 'food',
        没有: 'not have; there is not', 早上: 'morning', 这个: 'this one',
        那个: 'that one', 这里: 'здесь', 那里: 'там',
        大小: 'размер', 多少: 'how many; how much', 上下: 'up and down; roughly',
        十五: 'fifteen', 五十: 'fifty', 三十: 'thirty',
        今天: 'сегодня', 明天: 'завтра', 天上: 'in the sky',
        早晚: 'sooner or later; morning and evening', 日月: 'sun and moon', 人口: 'population',
        耳目: 'what one sees and hears', 手中: 'in hand', 水中: 'in the water',
        山口: 'mountain pass', 山水: 'landscape', 火山: 'volcano',
        水土: 'water and soil; climate', 田里: 'in the field', 山下: 'at the foot of the mountain',
        石头: 'stone', 天下: 'the world; all under heaven', 水里: 'in the water',
        手上: 'in the hand', 土里: 'in the soil', 大人: 'adult',
        好人: 'good person', 明日: 'tomorrow (formal)', 今日: 'today (formal)',
        水火: 'water and fire',
    },
    'fr': {
        a: 'un; une', i: 'je; moi', do: 'faire',
        go: 'aller', up: 'vers le haut', no: 'non',
        it: 'cela; le', is: 'être (3e pers.)', in: 'dans',
        on: 'sur', to: 'à; vers', we: 'nous',
        he: 'il', me: 'moi', red: 'rouge',
        blue: 'bleu', green: 'vert', yellow: 'jaune',
        cat: 'chat', dog: 'chien', sun: 'soleil',
        run: 'courir', eat: 'manger', box: 'boîte',
        love: 'aimer; amour', time: 'temps; heure', book: 'livre',
        milk: 'lait', apple: 'pomme', water: 'eau',
        house: 'maison', music: 'musique', fish: 'poisson',
        bird: 'oiseau', star: 'étoile', egg: 'œuf',
        fight: 'se battre', ball: 'ballon', tree: 'arbre',
        discovery: 'découverte', you: 'tu; vous', she: 'elle',
        need: 'avoir besoin', food: 'nourriture', drink: 'boire',
        sleep: 'dormir', what: 'quoi; que', teach: 'enseigner',
        learn: 'apprendre', help: 'aider', eye: 'œil',
        ear: 'oreille', mouth: 'bouche', nose: 'nez',
        hand: 'main', idea: 'idée', door: 'porte',
        bed: 'lit', chair: 'chaise', table: 'table',
        cup: 'tasse', bowl: 'bol', open: 'ouvrir',
        close: 'fermer', light: 'lumière; lampe', thanks: 'merci',
        smile: 'sourire', hello: 'bonjour', walk: 'marcher',
        talk: 'parler', я: 'je; moi', а: 'et; mais',
        да: 'oui', нет: 'non', он: 'il',
        мы: 'nous', кот: 'chat', дом: 'maison',
        сыр: 'fromage', чай: 'thé', мяч: 'ballon',
        мама: 'maman', папа: 'papa', вода: 'eau',
        окно: 'fenêtre', небо: 'ciel', рыба: 'poisson',
        рука: 'main; bras', красный: 'rouge', синий: 'bleu',
        зелёный: 'vert', собака: 'chien', погода: 'temps (météo)',
        молоко: 'lait', спасибо: 'merci', 你: 'tu; vous',
        我: 'je; moi', 他: 'il', 她: 'elle',
        们: 'suffixe pluriel', 好: 'bon; bien', 是: 'être; oui',
        在: 'être à; exister', 不: 'ne... pas', 有: 'avoir; il y a',
        吃: 'manger', 喝: 'boire', 食: 'nourriture',
        物: 'chose; objet', 水: 'eau', 谢: 'remercier',
        再: 'encore', 见: 'voir; se voir', 晚: 'soir; tard',
        安: 'paisible', 什: 'quoi (什么)', 这: 'ceci',
        那: 'cela', 哪: 'où; lequel', 吗: 'particule interrogative',
        大: 'grand', 小: 'petit', 多: 'beaucoup',
        少: 'peu', 上: 'haut; sur', 下: 'bas; sous',
        中: 'milieu; dans', 天: 'ciel; jour', 月: 'lune; mois',
        日: 'soleil; jour', 人: 'personne', 口: 'bouche',
        手: 'main', 目: 'œil', 耳: 'oreille',
        一: 'un', 二: 'deux', 三: 'trois',
        四: 'quatre', 五: 'cinq', 山: 'montagne',
        火: 'feu', 石: 'pierre', 田: 'champ',
        土: 'terre', they: 'ils; elles', us: 'nous',
        them: 'les; leur', my: 'mon; ma', your: 'ton; votre',
        his: 'son (à lui)', her: 'son (à elle)', its: 'son (à cela)',
        our: 'notre', want: 'vouloir', have: 'avoir',
        use: 'utiliser', get: 'obtenir', hungry: 'avoir faim',
        rice: 'riz', bread: 'pain', noodle: 'nouilles',
        meat: 'viande', dream: 'rêve', tired: 'fatigué',
        night: 'nuit', who: 'qui', where: 'où',
        when: 'quand', why: 'pourquoi', how: 'comment',
        because: 'parce que', if: 'si', and: 'et',
        but: 'mais', please: 's\'il vous plaît', give: 'donner',
        face: 'visage', foot: 'pied', leg: 'jambe',
        arm: 'bras', head: 'tête', see: 'voir',
        look: 'regarder', hear: 'entendre', listen: 'écouter',
        speak: 'parler', think: 'penser', know: 'savoir; connaître',
        feel: 'ressentir', mind: 'esprit', home: 'maison; chez soi',
        room: 'chambre; pièce', key: 'clé', lock: 'serrure',
        desk: 'bureau', sofa: 'canapé', shelf: 'étagère',
        plate: 'assiette', spoon: 'cuillère', chopsticks: 'baguettes',
        fork: 'fourchette', knife: 'couteau', cook: 'cuisiner',
        kitchen: 'cuisine', bottle: 'bouteille', bag: 'sac',
        clothes: 'vêtements', shirt: 'chemise', shoe: 'chaussure',
        nǐhǎo: 'bonjour', wǒmen: 'nous', xièxie: 'merci',
        zàijiàn: 'au revoir', wǎnān: 'bonne nuit', shénme: 'quoi',
        zhèlǐ: 'ici', nàlǐ: 'là-bas', xiànzài: 'maintenant',
        jīntiān: 'aujourd\'hui', míngtiān: 'demain', xuésheng: 'étudiant',
        lǎoshī: 'professeur', péngyou: 'ami', shuǐguǒ: 'fruits',
        chīfàn: 'prendre un repas', hēshuǐ: 'boire de l\'eau', shǒujī: 'téléphone portable',
        diànnǎo: 'ordinateur', dàxiǎo: 'taille', 你好: 'bonjour',
        谢谢: 'merci', 再见: 'au revoir', 晚安: 'bonne nuit',
        你们: 'you (plural)', 我们: 'nous', 他们: 'they',
        她们: 'they (women)', 什么: 'quoi', 不是: 'is not',
        吃饭: 'prendre un repas', 喝水: 'boire de l\'eau', 食物: 'food',
        没有: 'not have; there is not', 早上: 'morning', 这个: 'this one',
        那个: 'that one', 这里: 'ici', 那里: 'là-bas',
        大小: 'taille', 多少: 'how many; how much', 上下: 'up and down; roughly',
        十五: 'fifteen', 五十: 'fifty', 三十: 'thirty',
        今天: 'aujourd\'hui', 明天: 'demain', 天上: 'in the sky',
        早晚: 'sooner or later; morning and evening', 日月: 'sun and moon', 人口: 'population',
        耳目: 'what one sees and hears', 手中: 'in hand', 水中: 'in the water',
        山口: 'mountain pass', 山水: 'landscape', 火山: 'volcano',
        水土: 'water and soil; climate', 田里: 'in the field', 山下: 'at the foot of the mountain',
        石头: 'stone', 天下: 'the world; all under heaven', 水里: 'in the water',
        手上: 'in the hand', 土里: 'in the soil', 大人: 'adult',
        好人: 'good person', 明日: 'tomorrow (formal)', 今日: 'today (formal)',
        水火: 'water and fire',
    },
    'de': {
        a: 'ein; eine', i: 'ich', do: 'tun; machen',
        go: 'gehen', up: 'nach oben', no: 'nein',
        it: 'es', is: 'ist (3. Person)', in: 'in',
        on: 'auf', to: 'zu; nach', we: 'wir',
        he: 'er', me: 'ich; mir', red: 'rot',
        blue: 'blau', green: 'grün', yellow: 'gelb',
        cat: 'Katze', dog: 'Hund', sun: 'Sonne',
        run: 'laufen', eat: 'essen', box: 'Kiste',
        love: 'Liebe; lieben', time: 'Zeit', book: 'Buch',
        milk: 'Milch', apple: 'Apfel', water: 'Wasser',
        house: 'Haus', music: 'Musik', fish: 'Fisch',
        bird: 'Vogel', star: 'Stern', egg: 'Ei',
        fight: 'kämpfen', ball: 'Ball', tree: 'Baum',
        discovery: 'Entdeckung', you: 'du; Sie', she: 'sie',
        need: 'brauchen', food: 'Essen; Lebensmittel', drink: 'trinken',
        sleep: 'schlafen', what: 'was', teach: 'lehren',
        learn: 'lernen', help: 'helfen', eye: 'Auge',
        ear: 'Ohr', mouth: 'Mund', nose: 'Nase',
        hand: 'Hand', idea: 'Idee', door: 'Tür',
        bed: 'Bett', chair: 'Stuhl', table: 'Tisch',
        cup: 'Tasse', bowl: 'Schüssel', open: 'öffnen',
        close: 'schließen', light: 'Licht; Lampe', thanks: 'danke',
        smile: 'Lächeln', hello: 'hallo', walk: 'gehen; spazieren',
        talk: 'sprechen; reden', я: 'ich', а: 'und; aber',
        да: 'ja', нет: 'nein', он: 'er',
        мы: 'wir', кот: 'Kater; Katze', дом: 'Haus',
        сыр: 'Käse', чай: 'Tee', мяч: 'Ball',
        мама: 'Mama', папа: 'Papa', вода: 'Wasser',
        окно: 'Fenster', небо: 'Himmel', рыба: 'Fisch',
        рука: 'Hand; Arm', красный: 'rot', синий: 'blau',
        зелёный: 'grün', собака: 'Hund', погода: 'Wetter',
        молоко: 'Milch', спасибо: 'danke', 你: 'du; Sie',
        我: 'ich', 他: 'er', 她: 'sie',
        们: 'Mehrzahl-Endung', 好: 'gut', 是: 'sein; ja',
        在: 'sein in; existieren', 不: 'nicht', 有: 'haben; es gibt',
        吃: 'essen', 喝: 'trinken', 食: 'Essen',
        物: 'Ding; Gegenstand', 水: 'Wasser', 谢: 'danken',
        再: 'wieder', 见: 'sehen; treffen', 晚: 'Abend; spät',
        安: 'friedlich', 什: 'was (什么)', 这: 'dies',
        那: 'das', 哪: 'wo; welcher', 吗: 'Fragepartikel',
        大: 'groß', 小: 'klein', 多: 'viel',
        少: 'wenig', 上: 'oben; auf', 下: 'unten; unter',
        中: 'Mitte; in', 天: 'Himmel; Tag', 月: 'Mond; Monat',
        日: 'Sonne; Tag', 人: 'Mensch; Person', 口: 'Mund',
        手: 'Hand', 目: 'Auge', 耳: 'Ohr',
        一: 'eins', 二: 'zwei', 三: 'drei',
        四: 'vier', 五: 'fünf', 山: 'Berg',
        火: 'Feuer', 石: 'Stein', 田: 'Feld',
        土: 'Erde', they: 'sie (Plural)', us: 'uns',
        them: 'sie (Akk.)', my: 'mein', your: 'dein; Ihr',
        his: 'sein', her: 'ihr', its: 'sein (Sache)',
        our: 'unser', want: 'wollen', have: 'haben',
        use: 'benutzen', get: 'bekommen', hungry: 'hungrig',
        rice: 'Reis', bread: 'Brot', noodle: 'Nudel',
        meat: 'Fleisch', dream: 'Traum', tired: 'müde',
        night: 'Nacht', who: 'wer', where: 'wo',
        when: 'wann', why: 'warum', how: 'wie',
        because: 'weil', if: 'wenn', and: 'und',
        but: 'aber', please: 'bitte', give: 'geben',
        face: 'Gesicht', foot: 'Fuß', leg: 'Bein',
        arm: 'Arm', head: 'Kopf', see: 'sehen',
        look: 'schauen', hear: 'hören', listen: 'zuhören',
        speak: 'sprechen', think: 'denken', know: 'wissen; kennen',
        feel: 'fühlen', mind: 'Verstand', home: 'Zuhause',
        room: 'Zimmer', key: 'Schlüssel', lock: 'Schloss',
        desk: 'Schreibtisch', sofa: 'Sofa', shelf: 'Regal',
        plate: 'Teller', spoon: 'Löffel', chopsticks: 'Essstäbchen',
        fork: 'Gabel', knife: 'Messer', cook: 'kochen',
        kitchen: 'Küche', bottle: 'Flasche', bag: 'Tasche',
        clothes: 'Kleidung', shirt: 'Hemd', shoe: 'Schuh',
        nǐhǎo: 'hallo', wǒmen: 'wir', xièxie: 'danke',
        zàijiàn: 'auf Wiedersehen', wǎnān: 'gute Nacht', shénme: 'was',
        zhèlǐ: 'hier', nàlǐ: 'dort', xiànzài: 'jetzt',
        jīntiān: 'heute', míngtiān: 'morgen', xuésheng: 'Student; Schüler',
        lǎoshī: 'Lehrer', péngyou: 'Freund', shuǐguǒ: 'Obst',
        chīfàn: 'essen (Mahlzeit)', hēshuǐ: 'Wasser trinken', shǒujī: 'Handy',
        diànnǎo: 'Computer', dàxiǎo: 'Größe', 你好: 'hallo',
        谢谢: 'danke', 再见: 'auf Wiedersehen', 晚安: 'gute Nacht',
        你们: 'you (plural)', 我们: 'wir', 他们: 'they',
        她们: 'they (women)', 什么: 'was', 不是: 'is not',
        吃饭: 'essen (Mahlzeit)', 喝水: 'Wasser trinken', 食物: 'food',
        没有: 'not have; there is not', 早上: 'morning', 这个: 'this one',
        那个: 'that one', 这里: 'hier', 那里: 'dort',
        大小: 'Größe', 多少: 'how many; how much', 上下: 'up and down; roughly',
        十五: 'fifteen', 五十: 'fifty', 三十: 'thirty',
        今天: 'heute', 明天: 'morgen', 天上: 'in the sky',
        早晚: 'sooner or later; morning and evening', 日月: 'sun and moon', 人口: 'population',
        耳目: 'what one sees and hears', 手中: 'in hand', 水中: 'in the water',
        山口: 'mountain pass', 山水: 'landscape', 火山: 'volcano',
        水土: 'water and soil; climate', 田里: 'in the field', 山下: 'at the foot of the mountain',
        石头: 'stone', 天下: 'the world; all under heaven', 水里: 'in the water',
        手上: 'in the hand', 土里: 'in the soil', 大人: 'adult',
        好人: 'good person', 明日: 'tomorrow (formal)', 今日: 'today (formal)',
        水火: 'water and fire',
    },
    'es': {
        a: 'un; una', i: 'yo', do: 'hacer',
        go: 'ir', up: 'arriba', no: 'no',
        it: 'eso; lo', is: 'es (3.ª pers.)', in: 'en; dentro',
        on: 'sobre; en', to: 'a; hacia', we: 'nosotros',
        he: 'él', me: 'mí; me', red: 'rojo',
        blue: 'azul', green: 'verde', yellow: 'amarillo',
        cat: 'gato', dog: 'perro', sun: 'sol',
        run: 'correr', eat: 'comer', box: 'caja',
        love: 'amor; amar', time: 'tiempo; hora', book: 'libro',
        milk: 'leche', apple: 'manzana', water: 'agua',
        house: 'casa', music: 'música', fish: 'pez; pescado',
        bird: 'pájaro', star: 'estrella', egg: 'huevo',
        fight: 'pelear; luchar', ball: 'pelota; balón', tree: 'árbol',
        discovery: 'descubrimiento', you: 'tú; usted', she: 'ella',
        need: 'necesitar', food: 'comida', drink: 'beber',
        sleep: 'dormir', what: 'qué', teach: 'enseñar',
        learn: 'aprender', help: 'ayudar', eye: 'ojo',
        ear: 'oreja', mouth: 'boca', nose: 'nariz',
        hand: 'mano', idea: 'idea', door: 'puerta',
        bed: 'cama', chair: 'silla', table: 'mesa',
        cup: 'taza', bowl: 'bol; cuenco', open: 'abrir',
        close: 'cerrar', light: 'luz; lámpara', thanks: 'gracias',
        smile: 'sonrisa; sonreír', hello: 'hola', walk: 'caminar',
        talk: 'hablar', я: 'yo', а: 'y; pero',
        да: 'sí', нет: 'no', он: 'él',
        мы: 'nosotros', кот: 'gato', дом: 'casa',
        сыр: 'queso', чай: 'té', мяч: 'pelota',
        мама: 'mamá', папа: 'papá', вода: 'agua',
        окно: 'ventana', небо: 'cielo', рыба: 'pez',
        рука: 'mano; brazo', красный: 'rojo', синий: 'azul',
        зелёный: 'verde', собака: 'perro', погода: 'tiempo (clima)',
        молоко: 'leche', спасибо: 'gracias', 你: 'tú',
        我: 'yo', 他: 'él', 她: 'ella',
        们: 'sufijo plural', 好: 'bueno', 是: 'ser; sí',
        在: 'estar en; existir', 不: 'no', 有: 'tener; haber',
        吃: 'comer', 喝: 'beber', 食: 'comida',
        物: 'cosa', 水: 'agua', 谢: 'agradecer',
        再: 'otra vez', 见: 'ver; encontrarse', 晚: 'noche; tarde',
        安: 'tranquilo', 什: 'qué (什么)', 这: 'esto',
        那: 'eso', 哪: 'dónde; cuál', 吗: 'partícula interrogativa',
        大: 'grande', 小: 'pequeño', 多: 'mucho',
        少: 'poco', 上: 'arriba; sobre', 下: 'abajo; bajo',
        中: 'centro; en', 天: 'cielo; día', 月: 'luna; mes',
        日: 'sol; día', 人: 'persona', 口: 'boca',
        手: 'mano', 目: 'ojo', 耳: 'oreja',
        一: 'uno', 二: 'dos', 三: 'tres',
        四: 'cuatro', 五: 'cinco', 山: 'montaña',
        火: 'fuego', 石: 'piedra', 田: 'campo',
        土: 'tierra', they: 'ellos; ellas', us: 'nos',
        them: 'los; les', my: 'mi', your: 'tu; su',
        his: 'su (de él)', her: 'su (de ella)', its: 'su (de eso)',
        our: 'nuestro', want: 'querer', have: 'tener',
        use: 'usar', get: 'obtener', hungry: 'hambriento',
        rice: 'arroz', bread: 'pan', noodle: 'fideo; tallarín',
        meat: 'carne', dream: 'sueño', tired: 'cansado',
        night: 'noche', who: 'quién', where: 'dónde',
        when: 'cuándo', why: 'por qué', how: 'cómo',
        because: 'porque', if: 'si', and: 'y',
        but: 'pero', please: 'por favor', give: 'dar',
        face: 'cara; rostro', foot: 'pie', leg: 'pierna',
        arm: 'brazo', head: 'cabeza', see: 'ver',
        look: 'mirar', hear: 'oír', listen: 'escuchar',
        speak: 'hablar', think: 'pensar', know: 'saber; conocer',
        feel: 'sentir', mind: 'mente', home: 'hogar; casa',
        room: 'habitación; cuarto', key: 'llave', lock: 'cerradura',
        desk: 'escritorio', sofa: 'sofá', shelf: 'estante',
        plate: 'plato', spoon: 'cuchara', chopsticks: 'palillos',
        fork: 'tenedor', knife: 'cuchillo', cook: 'cocinar',
        kitchen: 'cocina', bottle: 'botella', bag: 'bolsa; bolso',
        clothes: 'ropa', shirt: 'camisa', shoe: 'zapato',
        nǐhǎo: 'hola', wǒmen: 'nosotros', xièxie: 'gracias',
        zàijiàn: 'adiós', wǎnān: 'buenas noches', shénme: 'qué',
        zhèlǐ: 'aquí', nàlǐ: 'allí', xiànzài: 'ahora',
        jīntiān: 'hoy', míngtiān: 'mañana', xuésheng: 'estudiante',
        lǎoshī: 'maestro; profesor', péngyou: 'amigo', shuǐguǒ: 'fruta',
        chīfàn: 'comer (comida)', hēshuǐ: 'beber agua', shǒujī: 'teléfono móvil',
        diànnǎo: 'computadora', dàxiǎo: 'tamaño', 你好: 'hola',
        谢谢: 'gracias', 再见: 'adiós', 晚安: 'buenas noches',
        你们: 'you (plural)', 我们: 'nosotros', 他们: 'they',
        她们: 'they (women)', 什么: 'qué', 不是: 'is not',
        吃饭: 'comer (comida)', 喝水: 'beber agua', 食物: 'food',
        没有: 'not have; there is not', 早上: 'morning', 这个: 'this one',
        那个: 'that one', 这里: 'aquí', 那里: 'allí',
        大小: 'tamaño', 多少: 'how many; how much', 上下: 'up and down; roughly',
        十五: 'fifteen', 五十: 'fifty', 三十: 'thirty',
        今天: 'hoy', 明天: 'mañana', 天上: 'in the sky',
        早晚: 'sooner or later; morning and evening', 日月: 'sun and moon', 人口: 'population',
        耳目: 'what one sees and hears', 手中: 'in hand', 水中: 'in the water',
        山口: 'mountain pass', 山水: 'landscape', 火山: 'volcano',
        水土: 'water and soil; climate', 田里: 'in the field', 山下: 'at the foot of the mountain',
        石头: 'stone', 天下: 'the world; all under heaven', 水里: 'in the water',
        手上: 'in the hand', 土里: 'in the soil', 大人: 'adult',
        好人: 'good person', 明日: 'tomorrow (formal)', 今日: 'today (formal)',
        水火: 'water and fire',
    },
    'pt': {
        a: 'um; uma', i: 'eu', do: 'fazer',
        go: 'ir', up: 'para cima', no: 'não',
        it: 'isso; o', is: 'é (3.ª pes.)', in: 'em; dentro',
        on: 'sobre; em', to: 'para; a', we: 'nós',
        he: 'ele', me: 'eu; mim', red: 'vermelho',
        blue: 'azul', green: 'verde', yellow: 'amarelo',
        cat: 'gato', dog: 'cão; cachorro', sun: 'sol',
        run: 'correr', eat: 'comer', box: 'caixa',
        love: 'amor; amar', time: 'tempo; hora', book: 'livro',
        milk: 'leite', apple: 'maçã', water: 'água',
        house: 'casa', music: 'música', fish: 'peixe',
        bird: 'pássaro', star: 'estrela', egg: 'ovo',
        fight: 'lutar; brigar', ball: 'bola', tree: 'árvore',
        discovery: 'descoberta', you: 'você; tu', she: 'ela',
        need: 'precisar', food: 'comida', drink: 'beber',
        sleep: 'dormir', what: 'que; o quê', teach: 'ensinar',
        learn: 'aprender', help: 'ajudar', eye: 'olho',
        ear: 'orelha', mouth: 'boca', nose: 'nariz',
        hand: 'mão', idea: 'ideia', door: 'porta',
        bed: 'cama', chair: 'cadeira', table: 'mesa',
        cup: 'caneca; xícara', bowl: 'tigela', open: 'abrir',
        close: 'fechar', light: 'luz; lâmpada', thanks: 'obrigado',
        smile: 'sorriso; sorrir', hello: 'olá', walk: 'andar; caminhar',
        talk: 'falar; conversar', я: 'eu', а: 'e; mas',
        да: 'sim', нет: 'não', он: 'ele',
        мы: 'nós', кот: 'gato', дом: 'casa',
        сыр: 'queijo', чай: 'chá', мяч: 'bola',
        мама: 'mamãe', папа: 'papai', вода: 'água',
        окно: 'janela', небо: 'céu', рыба: 'peixe',
        рука: 'mão; braço', красный: 'vermelho', синий: 'azul',
        зелёный: 'verde', собака: 'cachorro', погода: 'tempo (clima)',
        молоко: 'leite', спасибо: 'obrigado', 你: 'você',
        我: 'eu', 他: 'ele', 她: 'ela',
        们: 'sufixo plural', 好: 'bom; bem', 是: 'ser; sim',
        在: 'estar em; existir', 不: 'não', 有: 'ter; haver',
        吃: 'comer', 喝: 'beber', 食: 'comida',
        物: 'coisa', 水: 'água', 谢: 'agradecer',
        再: 'de novo', 见: 'ver; encontrar', 晚: 'noite; tarde',
        安: 'tranquilo', 什: 'que (什么)', 这: 'isto',
        那: 'aquilo', 哪: 'onde; qual', 吗: 'partícula interrogativa',
        大: 'grande', 小: 'pequeno', 多: 'muito',
        少: 'pouco', 上: 'cima; sobre', 下: 'baixo; embaixo',
        中: 'meio; em', 天: 'céu; dia', 月: 'lua; mês',
        日: 'sol; dia', 人: 'pessoa', 口: 'boca',
        手: 'mão', 目: 'olho', 耳: 'orelha',
        一: 'um', 二: 'dois', 三: 'três',
        四: 'quatro', 五: 'cinco', 山: 'montanha',
        火: 'fogo', 石: 'pedra', 田: 'campo',
        土: 'terra', they: 'eles; elas', us: 'nós',
        them: 'os; lhes', my: 'meu; minha', your: 'seu; teu',
        his: 'seu (dele)', her: 'seu (dela)', its: 'seu (disso)',
        our: 'nosso', want: 'querer', have: 'ter',
        use: 'usar', get: 'obter', hungry: 'com fome',
        rice: 'arroz', bread: 'pão', noodle: 'macarrão',
        meat: 'carne', dream: 'sonho', tired: 'cansado',
        night: 'noite', who: 'quem', where: 'onde',
        when: 'quando', why: 'por que', how: 'como',
        because: 'porque', if: 'se', and: 'e',
        but: 'mas', please: 'por favor', give: 'dar',
        face: 'rosto; cara', foot: 'pé', leg: 'perna',
        arm: 'braço', head: 'cabeça', see: 'ver',
        look: 'olhar', hear: 'ouvir', listen: 'escutar',
        speak: 'falar', think: 'pensar', know: 'saber; conhecer',
        feel: 'sentir', mind: 'mente', home: 'lar; casa',
        room: 'quarto; sala', key: 'chave', lock: 'fechadura',
        desk: 'escrivaninha', sofa: 'sofá', shelf: 'prateleira',
        plate: 'prato', spoon: 'colher', chopsticks: 'hashis; palitos',
        fork: 'garfo', knife: 'faca', cook: 'cozinhar',
        kitchen: 'cozinha', bottle: 'garrafa', bag: 'bolsa; saco',
        clothes: 'roupas', shirt: 'camisa', shoe: 'sapato',
        nǐhǎo: 'olá', wǒmen: 'nós', xièxie: 'obrigado',
        zàijiàn: 'tchau; até logo', wǎnān: 'boa noite', shénme: 'o quê',
        zhèlǐ: 'aqui', nàlǐ: 'ali; lá', xiànzài: 'agora',
        jīntiān: 'hoje', míngtiān: 'amanhã', xuésheng: 'estudante',
        lǎoshī: 'professor', péngyou: 'amigo', shuǐguǒ: 'fruta',
        chīfàn: 'fazer uma refeição', hēshuǐ: 'beber água', shǒujī: 'celular',
        diànnǎo: 'computador', dàxiǎo: 'tamanho', 你好: 'olá',
        谢谢: 'obrigado', 再见: 'tchau; até logo', 晚安: 'boa noite',
        你们: 'you (plural)', 我们: 'nós', 他们: 'they',
        她们: 'they (women)', 什么: 'o quê', 不是: 'is not',
        吃饭: 'fazer uma refeição', 喝水: 'beber água', 食物: 'food',
        没有: 'not have; there is not', 早上: 'morning', 这个: 'this one',
        那个: 'that one', 这里: 'aqui', 那里: 'ali; lá',
        大小: 'tamanho', 多少: 'how many; how much', 上下: 'up and down; roughly',
        十五: 'fifteen', 五十: 'fifty', 三十: 'thirty',
        今天: 'hoje', 明天: 'amanhã', 天上: 'in the sky',
        早晚: 'sooner or later; morning and evening', 日月: 'sun and moon', 人口: 'population',
        耳目: 'what one sees and hears', 手中: 'in hand', 水中: 'in the water',
        山口: 'mountain pass', 山水: 'landscape', 火山: 'volcano',
        水土: 'water and soil; climate', 田里: 'in the field', 山下: 'at the foot of the mountain',
        石头: 'stone', 天下: 'the world; all under heaven', 水里: 'in the water',
        手上: 'in the hand', 土里: 'in the soil', 大人: 'adult',
        好人: 'good person', 明日: 'tomorrow (formal)', 今日: 'today (formal)',
        水火: 'water and fire',
    },
    'ar': {
        a: 'واحد; أي', i: 'أنا', do: 'يفعل',
        go: 'يذهب', up: 'إلى الأعلى', no: 'لا',
        it: 'هو/هي (لغير العاقل)', is: 'يكون (للغائب)', in: 'في',
        on: 'على', to: 'إلى', we: 'نحن',
        he: 'هو', me: 'أنا; إياي', red: 'أحمر',
        blue: 'أزرق', green: 'أخضر', yellow: 'أصفر',
        cat: 'قط', dog: 'كلب', sun: 'شمس',
        run: 'يجري; يركض', eat: 'يأكل', box: 'صندوق',
        love: 'يحب; حب', time: 'وقت', book: 'كتاب',
        milk: 'حليب', apple: 'تفاحة', water: 'ماء',
        house: 'بيت', music: 'موسيقى', fish: 'سمك',
        bird: 'طائر', star: 'نجم; نجمة', egg: 'بيضة',
        fight: 'يقاتل', ball: 'كرة', tree: 'شجرة',
        discovery: 'اكتشاف', you: 'أنت', she: 'هي',
        need: 'يحتاج', food: 'طعام', drink: 'يشرب',
        sleep: 'ينام', what: 'ماذا; ما', teach: 'يعلّم',
        learn: 'يتعلم', help: 'يساعد', eye: 'عين',
        ear: 'أذن', mouth: 'فم', nose: 'أنف',
        hand: 'يد', idea: 'فكرة', door: 'باب',
        bed: 'سرير', chair: 'كرسي', table: 'طاولة',
        cup: 'كوب', bowl: 'وعاء; زبدية', open: 'يفتح',
        close: 'يغلق', light: 'ضوء; مصباح', thanks: 'شكراً',
        smile: 'يبسم; ابتسامة', hello: 'مرحباً', walk: 'يمشي',
        talk: 'يتحدث', я: 'أنا', а: 'و; لكن',
        да: 'نعم', нет: 'لا', он: 'هو',
        мы: 'نحن', кот: 'قط', дом: 'بيت',
        сыр: 'جبن', чай: 'شاي', мяч: 'كرة',
        мама: 'أمي', папа: 'أبي', вода: 'ماء',
        окно: 'نافذة', небо: 'سماء', рыба: 'سمك',
        рука: 'يد; ذراع', красный: 'أحمر', синий: 'أزرق',
        зелёный: 'أخضر', собака: 'كلب', погода: 'طقس',
        молоко: 'حليب', спасибо: 'شكراً', 你: 'أنت',
        我: 'أنا', 他: 'هو', 她: 'هي',
        们: 'لواحق الجمع', 好: 'جيد', 是: 'يكون; نعم',
        在: 'في; يوجد', 不: 'لا; ليس', 有: 'لديه; يوجد',
        吃: 'يأكل', 喝: 'يشرب', 食: 'طعام',
        物: 'شيء', 水: 'ماء', 谢: 'يشكر',
        再: 'مرة أخرى', 见: 'يرى; يلتقي', 晚: 'مساء; متأخر',
        安: 'سلام; آمن', 什: 'ماذا (什么)', 这: 'هذا',
        那: 'ذلك', 哪: 'أين; أي', 吗: 'أداة استفهام',
        大: 'كبير', 小: 'صغير', 多: 'كثير',
        少: 'قليل', 上: 'أعلى; فوق', 下: 'أسفل; تحت',
        中: 'وسط; في', 天: 'سماء; يوم', 月: 'قمر; شهر',
        日: 'شمس; يوم', 人: 'شخص; إنسان', 口: 'فم',
        手: 'يد', 目: 'عين', 耳: 'أذن',
        一: 'واحد', 二: 'اثنان', 三: 'ثلاثة',
        四: 'أربعة', 五: 'خمسة', 山: 'جبل',
        火: 'نار', 石: 'حجر', 田: 'حقل',
        土: 'تراب; أرض', they: 'هم', us: 'إلينا; نا',
        them: 'لهم; هم', my: 'خاصتي', your: 'خاصتك',
        his: 'خاصته', her: 'خاصتها', its: 'خاصته (غير عاقل)',
        our: 'خاصتنا', want: 'يريد', have: 'يملك',
        use: 'يستخدم', get: 'يحصل على', hungry: 'جائع',
        rice: 'أرز', bread: 'خبز', noodle: 'نودلز; معكرونة',
        meat: 'لحم', dream: 'حلم', tired: 'متعب',
        night: 'ليل', who: 'من', where: 'أين',
        when: 'متى', why: 'لماذا', how: 'كيف',
        because: 'لأن', if: 'إذا; لو', and: 'و',
        but: 'لكن', please: 'من فضلك', give: 'يعطي',
        face: 'وجه', foot: 'قدم', leg: 'ساق; رجل',
        arm: 'ذراع', head: 'رأس', see: 'يرى',
        look: 'ينظر', hear: 'يسمع', listen: 'يستمع',
        speak: 'يتكلم', think: 'يفكر', know: 'يعرف',
        feel: 'يشعر', mind: 'عقل', home: 'منزل; بيت',
        room: 'غرفة', key: 'مفتاح', lock: 'قفل',
        desk: 'مكتب', sofa: 'أريكة', shelf: 'رف',
        plate: 'طبق', spoon: 'ملعقة', chopsticks: 'عيدان الطعام',
        fork: 'شوكة', knife: 'سكين', cook: 'يطبخ',
        kitchen: 'مطبخ', bottle: 'زجاجة', bag: 'حقيبة; كيس',
        clothes: 'ملابس', shirt: 'قميص', shoe: 'حذاء',
        nǐhǎo: 'مرحباً', wǒmen: 'نحن', xièxie: 'شكراً',
        zàijiàn: 'إلى اللقاء', wǎnān: 'تصبح على خير', shénme: 'ماذا',
        zhèlǐ: 'هنا', nàlǐ: 'هناك', xiànzài: 'الآن',
        jīntiān: 'اليوم', míngtiān: 'غداً', xuésheng: 'طالب',
        lǎoshī: 'معلم', péngyou: 'صديق', shuǐguǒ: 'فواكه',
        chīfàn: 'يتناول الطعام', hēshuǐ: 'يشرب الماء', shǒujī: 'هاتف محمول',
        diànnǎo: 'حاسوب', dàxiǎo: 'حجم', 你好: 'مرحباً',
        谢谢: 'شكراً', 再见: 'إلى اللقاء', 晚安: 'تصبح على خير',
        你们: 'you (plural)', 我们: 'نحن', 他们: 'they',
        她们: 'they (women)', 什么: 'ماذا', 不是: 'is not',
        吃饭: 'يتناول الطعام', 喝水: 'يشرب الماء', 食物: 'food',
        没有: 'not have; there is not', 早上: 'morning', 这个: 'this one',
        那个: 'that one', 这里: 'هنا', 那里: 'هناك',
        大小: 'حجم', 多少: 'how many; how much', 上下: 'up and down; roughly',
        十五: 'fifteen', 五十: 'fifty', 三十: 'thirty',
        今天: 'اليوم', 明天: 'غداً', 天上: 'in the sky',
        早晚: 'sooner or later; morning and evening', 日月: 'sun and moon', 人口: 'population',
        耳目: 'what one sees and hears', 手中: 'in hand', 水中: 'in the water',
        山口: 'mountain pass', 山水: 'landscape', 火山: 'volcano',
        水土: 'water and soil; climate', 田里: 'in the field', 山下: 'at the foot of the mountain',
        石头: 'stone', 天下: 'the world; all under heaven', 水里: 'in the water',
        手上: 'in the hand', 土里: 'in the soil', 大人: 'adult',
        好人: 'good person', 明日: 'tomorrow (formal)', 今日: 'today (formal)',
        水火: 'water and fire',
    },
    'zh-CN': {
        你好: '见面时打招呼的用语', 我们: '包括自己在内的若干人', 谢谢: '表达感谢的用语',
        再见: '分别时的告别用语', 晚安: '晚上分别或睡前的祝福语', 你们: '称呼对方的若干人',
        什么: '疑问词，询问事物', 不是: '对判断的否定', 吃饭: '进食；用餐',
        喝水: '喝水的动作；饮用水', 食物: '可以充饥的东西', 没有: '不存在；不具备',
        早上: '清晨的时间', 这个: '所指的近处事物', 那个: '所指的远处事物',
        这里: '此地；这个地方', 那里: '彼处；那个地方', 大小: '尺寸；程度',
        多少: '询问数量', 上下: '高处和低处；大约', 十五: '数字，十加五',
        五十: '数字，五个十', 三十: '数字，三个十', 今天: '说话时的这一天',
        明天: '今天的下一天', 天上: '天空中', 早晚: '清晨和晚上；迟早',
        日月: '太阳和月亮', 人口: '人的数量', 耳目: '耳朵和眼睛；见闻',
        手中: '手里', 水中: '水的里面', 山口: '山间的通道',
        山水: '山和水；风景', 火山: '会喷出岩浆的山', 水土: '土地和水源',
        田里: '田地之中', 山下: '山的下方', 石头: '石块',
        天下: '整个世界', 水里: '水的里面', 手上: '手里',
        土里: '泥土之中', 大人: '成年人', 好人: '品行善良的人',
        明日: '第二天；明天', 今日: '当天；今天', 水火: '水和火',
        你: '第二人称，称呼对方', 我: '第一人称，称呼自己', 他: '第三人称，称呼男性',
        她: '第三人称，称呼女性', 们: '复数后缀，表示群体', 好: '优点多的；令人满意的',
        是: '对；表示肯定判断', 在: '表示存在或位置', 不: '表示否定',
        有: '表示拥有或存在', 吃: '把食物放进嘴里咽下', 喝: '把液体咽下去',
        食: '吃的东西', 物: '东西；事物', 水: '无色无味的透明液体',
        谢: '表示感谢', 再: '又一次', 见: '看到；会面',
        晚: '日暮之后的时间', 安: '平安；安静', 什: '什么（疑问词）',
        这: '指代较近的人或事物', 那: '指代较远的人或事物', 哪: '疑问词，询问地点',
        吗: '疑问语气词', 大: '体积、面积、数量等超过一般', 小: '体积、数量等不及一般',
        多: '数量大', 少: '数量小', 上: '位置在高处',
        下: '位置在低处', 中: '中心；里面', 天: '天空；一昼夜',
        月: '月亮；一年的十二分之一', 日: '太阳；一昼夜', 人: '能制造工具的高等动物',
        口: '嘴；出入的通道', 手: '人体上肢前端带指的部分', 目: '眼睛',
        耳: '听觉器官', 一: '数字，最小的正整数', 二: '数字，一加一',
        三: '数字，二加一', 四: '数字，三加一', 五: '数字，四加一',
        山: '地面上隆起的巨大土石', 火: '物体燃烧发出的光焰', 石: '构成地壳的坚硬矿物',
        田: '种植农作物的土地', 土: '地面上的泥沙混合物', 手机: '随身携带的电话',
        电脑: '电子计算机', 老师: '在学校教书的人', 学生: '在学校学习的人',
        朋友: '彼此有交情的人', 水果: '多汁可食用的果实', 他们: 'they',
        她们: 'they (women)',
    },
};
