/* ============================================================
 * 中文学习数据：写字模式（词语化）+ 声调拼音词库（方块/填词/闯关通用）
 * 填词/闯关的键为带调拼音（如 nǐhǎo），字母块直接带声调；
 * ZH_DISPLAY 提供汉字显示；ZH_SYL 提供音节切分（声母韵母分组挖洞）
 * ============================================================ */
window.ZH_WORDS = {
        'ni': {mean: '你', hanzi: '你', img: '🈶', color: null},
        'wo': {mean: '我', hanzi: '我', img: '🈶', color: null},
        'ta': {mean: '他', hanzi: '他', img: '🈶', color: null},
        'hao': {mean: '好', hanzi: '好', img: '🈶', color: null},
        'bu': {mean: '不', hanzi: '不', img: '🈶', color: null},
        'you': {mean: '有', hanzi: '有', img: '🈶', color: null},
        'chi': {mean: '吃', hanzi: '吃', img: '🈶', color: null},
        'he': {mean: '喝', hanzi: '喝', img: '🈶', color: null},
        'shui': {mean: '水', hanzi: '水', img: '🈶', color: null},
        'da': {mean: '大', hanzi: '大', img: '🈶', color: null},
        'xiao': {mean: '小', hanzi: '小', img: '🈶', color: null},
        'duo': {mean: '多', hanzi: '多', img: '🈶', color: null},
        'shang': {mean: '上', hanzi: '上', img: '🈶', color: null},
        'xia': {mean: '下', hanzi: '下', img: '🈶', color: null},
        'ren': {mean: '人', hanzi: '人', img: '🈶', color: null},
        'kou': {mean: '口', hanzi: '口', img: '🈶', color: null},
        'shou': {mean: '手', hanzi: '手', img: '🈶', color: null},
        'mu': {mean: '目', hanzi: '目', img: '🈶', color: null},
        'tian': {mean: '天', hanzi: '天', img: '🈶', color: null},
        'yue': {mean: '月', hanzi: '月', img: '🈶', color: null},
        'ri': {mean: '日', hanzi: '日', img: '🈶', color: null},
        'shan': {mean: '山', hanzi: '山', img: '🈶', color: null},
        'huo': {mean: '火', hanzi: '火', img: '🈶', color: null},
        'shi': {mean: '是', hanzi: '是', img: '🈶', color: null}
};
window.ZH_DISPLAY = {"ni": "你", "wo": "我", "ta": "他", "hao": "好", "bu": "不", "you": "有", "chi": "吃", "he": "喝", "shui": "水", "da": "大", "xiao": "小", "duo": "多", "shang": "上", "xia": "下", "ren": "人", "kou": "口", "shou": "手", "mu": "目", "tian": "天", "yue": "月", "ri": "日", "shan": "山", "huo": "火", "shi": "是", "nǐhǎo": "你好", "wǒmen": "我们", "xièxie": "谢谢", "zàijiàn": "再见", "wǎnān": "晚安", "shénme": "什么", "zhèlǐ": "这里", "nàlǐ": "那里", "xiànzài": "现在", "jīntiān": "今天", "míngtiān": "明天", "xuésheng": "学生", "lǎoshī": "老师", "péngyou": "朋友", "shuǐguǒ": "水果", "chīfàn": "吃饭", "hēshuǐ": "喝水", "shǒujī": "手机", "diànnǎo": "电脑", "dàxiǎo": "大小"};
window.ZH_SYL = {"nǐhǎo":["nǐ","hǎo"],"wǒmen":["wǒ","men"],"xièxie":["xiè","xie"],"zàijiàn":["zài","jiàn"],"wǎnān":["wǎn","ān"],"shénme":["shén","me"],"zhèlǐ":["zhè","lǐ"],"nàlǐ":["nà","lǐ"],"xiànzài":["xiàn","zài"],"jīntiān":["jīn","tiān"],"míngtiān":["míng","tiān"],"xuésheng":["xué","sheng"],"lǎoshī":["lǎo","shī"],"péngyou":["péng","you"],"shuǐguǒ":["shuǐ","guǒ"],"chīfàn":["chī","fàn"],"hēshuǐ":["hē","shuǐ"],"shǒujī":["shǒu","jī"],"diànnǎo":["diàn","nǎo"],"dàxiǎo":["dà","xiǎo"],"nǐmen":["nǐ","men"],"búshì":["bú","shì"],"shíwù":["shí","wù"],"méiyǒu":["méi","yǒu"],"zǎoshang":["zǎo","shang"],"zhège":["zhè","ge"],"nàge":["nà","ge"],"duōshǎo":["duō","shǎo"],"shàngxià":["shàng","xià"],"shíwǔ":["shí","wǔ"],"wǔshí":["wǔ","shí"],"sānshí":["sān","shí"],"tiānshàng":["tiān","shàng"],"zǎowǎn":["zǎo","wǎn"],"rìyuè":["rì","yuè"],"rénkǒu":["rén","kǒu"],"ěrmù":["ěr","mù"],"shǒuzhōng":["shǒu","zhōng"],"shuǐzhōng":["shuǐ","zhōng"],"shānkǒu":["shān","kǒu"],"shānshuǐ":["shān","shuǐ"],"huǒshān":["huǒ","shān"],"shuǐtǔ":["shuǐ","tǔ"],"tiánlǐ":["tián","lǐ"],"shānxià":["shān","xià"],"shítou":["shí","tou"],"tiānxià":["tiān","xià"],"shuǐlǐ":["shuǐ","lǐ"],"shǒushàng":["shǒu","shàng"],"tǔlǐ":["tǔ","lǐ"],"dàrén":["dà","rén"],"hǎorén":["hǎo","rén"],"míngrì":["míng","rì"],"jīnrì":["jīn","rì"],"shuǐhuǒ":["shuǐ","huǒ"]};
window.ZH_PACK_LEVELS = [{"name":"中文起步1","words":[["nǐhǎo","你好"],["wǒmen","我们"],["xièxie","谢谢"],["zàijiàn","再见"],["wǎnān","晚安"]]},{"name":"中文起步2","words":[["shénme","什么"],["zhèlǐ","这里"],["nàlǐ","那里"],["xiànzài","现在"],["jīntiān","今天"]]},{"name":"中文起步3","words":[["míngtiān","明天"],["xuésheng","学生"],["lǎoshī","老师"],["péngyou","朋友"],["shuǐguǒ","水果"]]},{"name":"中文起步4","words":[["chīfàn","吃饭"],["hēshuǐ","喝水"],["shǒujī","手机"],["diànnǎo","电脑"],["dàxiǎo","大小"]]}];
window.ZH_WRITING_LEVELS = [{"name":"问候","words":[{"w":"你好","p":"nǐ hǎo","chars":["你","好"]},{"w":"谢谢","p":"xiè xie","chars":["谢","谢"]},{"w":"再见","p":"zài jiàn","chars":["再","见"]},{"w":"晚安","p":"wǎn ān","chars":["晚","安"]},{"w":"你们","p":"nǐ men","chars":["你","们"]}]},{"name":"人称","words":[{"w":"我们","p":"wǒ men","chars":["我","们"]},{"w":"他们","p":"tā men","chars":["他","们"]},{"w":"她们","p":"tā men","chars":["她","们"]},{"w":"什么","p":"shén me","chars":["什","么"]},{"w":"不是","p":"bú shì","chars":["不","是"]}]},{"name":"吃喝","words":[{"w":"吃饭","p":"chī fàn","chars":["吃","饭"]},{"w":"喝水","p":"hē shuǐ","chars":["喝","水"]},{"w":"食物","p":"shí wù","chars":["食","物"]},{"w":"没有","p":"méi yǒu","chars":["没","有"]},{"w":"早上","p":"zǎo shang","chars":["早","上"]}]},{"name":"指代","words":[{"w":"这个","p":"zhè ge","chars":["这","个"]},{"w":"那个","p":"nà ge","chars":["那","个"]},{"w":"这里","p":"zhè lǐ","chars":["这","里"]},{"w":"那里","p":"nà lǐ","chars":["那","里"]},{"w":"大小","p":"dà xiǎo","chars":["大","小"]}]},{"name":"数量","words":[{"w":"多少","p":"duō shǎo","chars":["多","少"]},{"w":"上下","p":"shàng xià","chars":["上","下"]},{"w":"十五","p":"shí wǔ","chars":["十","五"]},{"w":"五十","p":"wǔ shí","chars":["五","十"]},{"w":"三十","p":"sān shí","chars":["三","十"]}]},{"name":"时间","words":[{"w":"今天","p":"jīn tiān","chars":["今","天"]},{"w":"明天","p":"míng tiān","chars":["明","天"]},{"w":"天上","p":"tiān shàng","chars":["天","上"]},{"w":"早晚","p":"zǎo wǎn","chars":["早","晚"]},{"w":"日月","p":"rì yuè","chars":["日","月"]}]},{"name":"身体","words":[{"w":"人口","p":"rén kǒu","chars":["人","口"]},{"w":"耳目","p":"ěr mù","chars":["耳","目"]},{"w":"手中","p":"shǒu zhōng","chars":["手","中"]},{"w":"水中","p":"shuǐ zhōng","chars":["水","中"]},{"w":"山口","p":"shān kǒu","chars":["山","口"]}]},{"name":"自然","words":[{"w":"山水","p":"shān shuǐ","chars":["山","水"]},{"w":"火山","p":"huǒ shān","chars":["火","山"]},{"w":"水土","p":"shuǐ tǔ","chars":["水","土"]},{"w":"田里","p":"tián lǐ","chars":["田","里"]},{"w":"山下","p":"shān xià","chars":["山","下"]}]},{"name":"生活","words":[{"w":"石头","p":"shí tou","chars":["石","头"]},{"w":"天下","p":"tiān xià","chars":["天","下"]},{"w":"水里","p":"shuǐ lǐ","chars":["水","里"]},{"w":"手上","p":"shǒu shàng","chars":["手","上"]},{"w":"土里","p":"tǔ lǐ","chars":["土","里"]}]},{"name":"人物","words":[{"w":"大人","p":"dà rén","chars":["大","人"]},{"w":"好人","p":"hǎo rén","chars":["好","人"]},{"w":"明日","p":"míng rì","chars":["明","日"]},{"w":"今日","p":"jīn rì","chars":["今","日"]},{"w":"水火","p":"shuǐ huǒ","chars":["水","火"]}]}];
window.ZH_EMOJI = {"你好":"👋","我们":"👥","你们":"👏","他们":"🧑‍🤝‍🧑","她们":"👩‍👩‍👦","谢谢":"🙏","再见":"👋","晚安":"🌙","什么":"❓","不是":"🚫","吃饭":"🍚","喝水":"🥤","食物":"🍱","没有":"🈚","早上":"🌅","这个":"👇","那个":"👆","这里":"📍","那里":"🧭","大小":"📏","多少":"🔢","上下":"↕️","十五":"🔢","五十":"💯","三十":"3️⃣","今天":"📅","明天":"🎫","天上":"☁️","早晚":"🕕","日月":"🌗","人口":"👥","耳目":"👂","手中":"✋","水中":"🌊","山口":"⛰️","山水":"🏞️","火山":"🌋","水土":"💧","田里":"🌾","山下":"⛰️","石头":"🪨","天下":"🌍","水里":"💧","手上":"🖐️","土里":"🟤","大人":"🧑","好人":"😇","明日":"🌅","今日":"📆","水火":"♨️","你":"👉","我":"🙋","他":"🧑","她":"👩","们":"👥","好":"👍","是":"✅","在":"📍","不":"🚫","有":"🎁","吃":"🍚","喝":"🥤","食":"🍱","物":"📦","水":"💧","谢":"🙏","再":"🔁","见":"👀","晚":"🌙","安":"😴","什":"❓","这":"👇","那":"👆","哪":"❓","吗":"❓","大":"🐘","小":"🐜","多":"⬆️","少":"⬇️","上":"⬆️","下":"⬇️","中":"🎯","天":"🌤️","月":"🌙","日":"☀️","人":"🧑","口":"👄","手":"✋","目":"👁️","耳":"👂","一":"1️⃣","二":"2️⃣","三":"3️⃣","四":"4️⃣","五":"5️⃣","山":"⛰️","火":"🔥","石":"🪨","田":"🌾","土":"🟤","xiànzài":"📖","xuésheng":"📖","lǎoshī":"📖","péngyou":"📖","shuǐguǒ":"📖","shǒujī":"📖","diànnǎo":"📖"};
window.ZH_PINYIN = {"你":"nǐ","好":"hǎo","你好":"nǐ hǎo","谢":"xie","谢谢":"xiè xie","再":"zài","见":"jiàn","再见":"zài jiàn","晚":"wǎn","安":"ān","晚安":"wǎn ān","们":"men","你们":"nǐ men","我":"wǒ","我们":"wǒ men","他":"tā","他们":"tā men","她":"tā","她们":"tā men","什":"shén","么":"me","什么":"shén me","不":"bú","是":"shì","不是":"bú shì","吃":"chī","饭":"fàn","吃饭":"chī fàn","喝":"hē","水":"shuǐ","喝水":"hē shuǐ","食":"shí","物":"wù","食物":"shí wù","没":"méi","有":"yǒu","没有":"méi yǒu","早":"zǎo","上":"shàng","早上":"zǎo shang","这":"zhè","个":"ge","这个":"zhè ge","那":"nà","那个":"nà ge","里":"lǐ","这里":"zhè lǐ","那里":"nà lǐ","大":"dà","小":"xiǎo","大小":"dà xiǎo","多":"duō","少":"shǎo","多少":"duō shǎo","下":"xià","上下":"shàng xià","十":"shí","五":"wǔ","十五":"shí wǔ","五十":"wǔ shí","三":"sān","三十":"sān shí","今":"jīn","天":"tiān","今天":"jīn tiān","明":"míng","明天":"míng tiān","天上":"tiān shàng","早晚":"zǎo wǎn","日":"rì","月":"yuè","日月":"rì yuè","人":"rén","口":"kǒu","人口":"rén kǒu","耳":"ěr","目":"mù","耳目":"ěr mù","手":"shǒu","中":"zhōng","手中":"shǒu zhōng","水中":"shuǐ zhōng","山":"shān","山口":"shān kǒu","山水":"shān shuǐ","火":"huǒ","火山":"huǒ shān","土":"tǔ","水土":"shuǐ tǔ","田":"tián","田里":"tián lǐ","山下":"shān xià","石":"shí","头":"tou","石头":"shí tou","天下":"tiān xià","水里":"shuǐ lǐ","手上":"shǒu shàng","土里":"tǔ lǐ","大人":"dà rén","好人":"hǎo rén","明日":"míng rì","今日":"jīn rì","水火":"shuǐ huǒ","nǐhǎo":"nǐ hǎo","wǒmen":"wǒ men","xièxie":"xiè xie","zàijiàn":"zài jiàn","wǎnān":"wǎn ān","shénme":"shén me","zhèlǐ":"zhè lǐ","nàlǐ":"nà lǐ","xiànzài":"xiàn zài","jīntiān":"jīn tiān","míngtiān":"míng tiān","xuésheng":"xué sheng","lǎoshī":"lǎo shī","péngyou":"péng you","shuǐguǒ":"shuǐ guǒ","chīfàn":"chī fàn","hēshuǐ":"hē shuǐ","shǒujī":"shǒu jī","diànnǎo":"diàn nǎo","dàxiǎo":"dà xiǎo","ni":"nǐ","wo":"wǒ","ta":"tā","hao":"hǎo","bu":"bú","you":"yǒu","chi":"chī","he":"hē","shui":"shuǐ","da":"dà","xiao":"xiǎo","duo":"duō","shang":"shàng","xia":"xià","ren":"rén","kou":"kǒu","shou":"shǒu","mu":"mù","tian":"tiān","yue":"yuè","ri":"rì","shan":"shān","huo":"huǒ","shi":"shì"};
